- name: create environment for virtual rpm package including cobbler cobbler-web libvirt koan
  hosts: buildserver
  sudo: True
  gather_facts: no
  remote_user: vagrant
  tasks:
  # password = vagrant
  - name: create user rpmbuilder
    user: name=rpmbuilder
          state=present
          createhome=yes
          password=$6$rounds=100000$aOCk2g3iiAQT96VQ$VUJKkY/hA8deTBnQz3W5iJGfpY6Q/AsLOdrkX21wHsOMGARP8mIOcokjlwRqYYU5JPzzAC8D7H7wMfEZ5nEKV1
  - name: copy ssh private key for rpmbuilder
    copy: src=~/.ssh/insecure_private_key
          dest=/home/rpmbuilder/.ssh/
          mode=400
  - name: install development tool
    yum: name="{{item}}"
         state=present
    with_items:
      - rpm-build
      - "@Development Tools"  
- name: build rpms
  hosts: buildserver
  gather_facts: no
  remote_user: rpmbuilder
  vars:
    Versions: [ "1.0.0" ]
  tasks:
    - shell: "/bin/echo  '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros"
    - shell: "/bin/echo  '%debug_package %{nil}' >> ~/.rpmmacros"
    - shell: "/bin/mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}"
    - shell: "/bin/mkdir -p ~/rpmbuild/SOURCES/cobbler-all-{{item}}"
      with_items: Versions
    - shell: "cd ~/rpmbuild/SOURCES/; mkdir -p cobbler-all-{{item}}/"
      with_items: Versions
    - shell: "cd ~/rpmbuild/SOURCES/; tar cvzf cobbler-all-{{item}}.tar.gz cobbler-all-{{item}}/"
      with_items: Versions
   
    - template: dest=~/rpmbuild/SPECS/cobbler-all-{{item}}.spec
                src=templates/cobbler-all-version.spec
      with_items: Versions
    - shell: /usr/bin/rpmbuild -bb ~/rpmbuild/SPECS/cobbler-all-{{item}}.spec
      with_items: Versions
    - fetch: src=~/rpmbuild/RPMS/noarch/cobbler-all-{{item}}-0.noarch.rpm
             dest=./release/
             flat=true
      with_items: Versions
